### ISSUE TITLE
VDI files

### ISSUE THREAD

**Issue by tiagoravache** [TurboPack/Abbrevia#1]
i'm using TAbZipper in my application, and when i compress vdi files all be fine, but the uncompress process results an error, like "your file is not valid or corrupt", someone know why this happened?

p.s.:sorry the english i'm brazilian

**Comment by romankassebaum** [comment]
I*ve seen that you posted the same question under sourceforge. Maybe there someone can help you. Otherwise you should attach a test project.

**Comment by tiagoravache** [comment]
Ok, thanks
