### ISSUE TITLE
Not an Abbrevia bug - ShellShock Inquiry

### ISSUE THREAD

**Issue by rsgrimes** [TurboPack/Abbrevia#12]
Just an idea...

I've finally recently upgraded my development environment from Delphi XE7 to Delphi 10.2.3 Tokyo (yeah, I'm still behind the times!), and in doing so, found it very cool to see this (and several other) package available in GetIt Package Manager (GPM).  Previously, I had come here (before that, SourceForge, and before that, purchased from TurboPower!) for the former TurboPower packages, but I found no support for ShellShock. I grabbed the latest from SourceForge (I think), but found a number of problems. I finally got it to work, but wished I could have just gotten it form GPM or here.

Do you have any plans to add that package here? Would you like someone to help a bit? I can certainly help with identifying what I've done and do a bit of testing...

**Comment by romankassebaum** [comment]
These components are simply to old. Don't use them in new projects.
