### ISSUE TITLE
After install I do not see TAbZipper, TAbZipKit and other in palette of Componets Delphi Rio 

### ISSUE THREAD

**Issue by ZeroGit2015** [TurboPack/Abbrevia#16]
After install I do not see TAbZipper, TAbZipKit and other in palette of Componets Delphi Rio .
I see 7 components only at Abbrevia folder. :(
System: Windows 10 20H2
![Abbrevia](https://user-images.githubusercontent.com/12425062/125157633-d6bb7f00-e174-11eb-9faf-a086ff420ba9.jpg)

**Comment by romankassebaum** [comment]
Could you please try to install the Sydney package into the Rio IDE, since the Sydney package is the only maintained one?

**Comment by ZeroGit2015** [comment]
Thank you, problem solved.
