### ISSUE TITLE
The component does not work on Android in Delphi 11

### ISSUE THREAD

**Issue by juanml1979** [TurboPack/Abbrevia#17]
Hello. 

I've installed the component without any problem. I've used the packages AbbreviaD.bpl and AbbreviaFMXDDesign.bpl located in the Alexandria folder. 

The component is installed ok in the ID. 

The problem is I Can't use in Android. 

It's easy to reproduce:  put a TAbZipper in a form. Compile with Android Platform target selected...

I have 67 compiler errors (see the attached files)

[compilermessages.txt](https://github.com/TurboPack/Abbrevia/files/7186710/compilermessages.txt)

Some of the errors are very strange to me. For example, the first error: "[DCC Error] AbUtils.pas(1079): E2023 Function needs result type" refenced the followin line in AbUtils.pas:

function AbDateTimeToDosFileDate(Value : TDateTime) : Integer;

What?. The function already has a result type (integer). 

Could you help me please?

**Comment by juanml1979** [comment]
A simple mistake on my part

**Comment by PetrPanSK** [comment]
Can you explan what was your mistake? Since I have the same on Delphi 10.4.4

**Comment by romankassebaum** [comment]
I could reproduce the issue. There was a missing "end;" under POSIX. I can compile now. Please try.

**Comment by PetrPanSK** [comment]
If I am right, mistake is in AbUtils.pas in AbDosFileDateToDateTime function:

```
>   try
>     Result := EncodeDate(Yr, Mo, Dy) + EncodeTime(Hr, Mn, S, 0);
>   except
>     on E: EConvertError do
>       Result := 0;
>   end; // <--- this is missing
> {$ENDIF UNIX}
```

Would be nice to let them know they have error there, but I haven't find any contact to developper of Abbrevia

**Comment by romankassebaum** [comment]
I already fixed this.
