### ISSUE TITLE
Bzip2 compression broken with Delphi 11

### ISSUE THREAD

**Issue by MPannier** [TurboPack/Abbrevia#19]
Hello,

the following code will raise an exception "EBZCompressionError" in "TBZCompressionStream.Seek" if compiled with Delphi 11:

> procedure TForm1.Button1Click(Sender: TObject);
var
  Source: TMemoryStream;
  CompressionStream: TStream;
  Dest: TMemoryStream;
begin
  Source := TMemoryStream.Create;
  try
    Source.LoadFromFile('C:\temp\temp.txt');
    Dest := TMemoryStream.Create;
    try
      CompressionStream := TBZCompressionStream.Create(bs1, dest);
      try
        CompressionStream.CopyFrom(Source, 0);
      finally
        CompressionStream.Free;
      end;
    finally
      Dest.Free;
    end;
  finally
    Source.Free;
  end;
end;

In Delphi 11 TStream.CopyFrom has changed a lot. I think this is the reason for the error.

**Comment by romankassebaum** [comment]
I can reproduce the issue. It is only an exception that occurs inside the IDE. You can ignore it. Here is a code snippet from System.Classes:

function TStream.CopyFrom(const Source: TStream; Count: Int64; BufferSize: Integer): Int64;
   ...
   try
      ...
    except
      // If Size/Position is not supported, or no NewSize space is available, or reallocation
      // is not supported, or stream is read-only, then ignore exception and let WriteBuffer
      // raise exception. Expectable exception classes are: EStreamError, EOSError, EOutOfMemory.
    end;

**Comment by MPannier** [comment]
Thanks for the reply. You are right. In my demo application, it works as you described. The exception will only be "visible" in the debugger and the zipped stream can be unzipped without problems. 

But I migrate an older project to Delphi 11 and there I will get the exception message "Invalid stream operation" from "TBZCompressionStream.Seek" without debugger. I can click OK and the compression will continue. The zipped stream is also correct and can be unzipped. But I get the exception message. I have checked ccompiler settings and can't find the one which causes the dialog to pop up. Any hints? Did you plan to rewrite the TBZCompressionStream class in future?

**Comment by bah111** [comment]
This probably has been fixed in D11.1 release.  EMB put a size check in the TStream.CopyFrom in D11, which for compressed streams is sometimes pointless.  They have done a fix and hence your problems might/should go away.
