### ISSUE TITLE
Compilation in Delphi 10 for android

### ISSUE THREAD

**Issue by holtis** [TurboPack/Abbrevia#2]
Hi, i have installed Delphi 10 Seattle trial version. With "Getit" i install Abbrevia TurboPack 10.0 ...components from packed have problem in compilation for android platform. When i use any component fro Abbrevia on blank form then i have in debugging this error:
[DCC Error] E2597 ....\prebuilt\windows\bin\arm-linux-androideabi-ld.exe: error: cannot find -lbz2
In compilation for windows is all OK.
How fix it?
Thanks you, Michal.

**Comment by romankassebaum** [comment]
I have the impression that bz2 doesn't work under Android. Therefore you can deactivate the bz2 support in the AbDefine.inc file. You can simply active the {$DEFINE NoBZip2} define.
