### ISSUE TITLE
TBZCompressionStream fail in D11

### ISSUE THREAD

**Issue by ofuncke** [TurboPack/Abbrevia#20]
Due to changes in System.Classes in Delphi 11, TBZCompressionStream.Seek fails, because it is called with soBeginning or soEnd. 
This has already been discussed in #19 but not yet solved.

Workaround:

```
function TBZCompressionStream.Seek(const Offset: Int64; Origin: TSeekOrigin): Int64;
var
  conv64 : TLargeInteger;
begin
  if (Offset = 0) and (Origin = soCurrent) then begin
    conv64.LowPart  := FBZRec.total_in_lo32;
    conv64.HighPart := FBZRec.total_in_hi32;
    Result := conv64.QuadPart;
  end
  else                                         // <<
  if (Origin in  [soBeginning, soEnd]) then    // <<  Workaround
    Result := 0                                // <<
  else
    raise EBZCompressionError.Create('Invalid stream operation');
end; { TBZCompressionStream }
```

**Comment by romankassebaum** [comment]
This would mean that a call like

MyBZCompressionStream.Seek(42, soBeginning) 

would return 0 and would not change anything. I'm not convinced.
Do you have a test project with an issue?

**Comment by ofuncke** [comment]
> Do you have a test project with an issue?

Yes: \Abbrevia-master\tests\AbBzip2Tests.pas:TAbBzip2Tests.TestCompressionStream

> would return 0 and would not change anything. I'm not convinced.
At compression time, the stream's size is undeterminable until the compression is finished. All FBZRec fields are 0.
