### ISSUE TITLE
Possibility to use TBufferedFileStream 

### ISSUE THREAD

**Issue by FernandoBanhos** [TurboPack/Abbrevia#26]
TBufferedFileStream is faster than TFileStream to write to Disk, I have 5gb files and they are taking 40 minutes to compress

**Comment by romankassebaum** [comment]
To which procedure are you referring? Do you think about procedure AbZip?

**Comment by FernandoBanhos** [comment]
Yes, I do Zip my files with encryption

**Comment by romankassebaum** [comment]
Okay, I replaced generally TFileStream by TBufferedFIleStream.
