### ISSUE TITLE
unit AbHexVw

### ISSUE THREAD

**Issue by ip74** [TurboPack/Abbrevia#3]
Line:
{$I AbDefine.inc}

Needs to go after:
unit AbHexVw;

Otherwise I get:
[Error] AbDefine.inc(99): Constant expression expected
[Fatal Error] AbbreviaVCL.dpk(70): Could not compile used unit '..\..\source\AbHexVw.pas'

**Comment by romankassebaum** [comment]
I just tried to compile with 10.1 Berlin with success.

**Comment by ip74** [comment]
Error confirmed.
Certain versions of Delphi won't allow IF conditionals before the UNIT line.
Also, the rest of the units in this project have the INCLUDE command after the UNIT line.
Older versions of this unit (AbHexVw) have it right.

**Comment by romankassebaum** [comment]
But this is a fork for 10.1 Berlin.
