### ISSUE TITLE
Invalid cast of pointer to Integer in AbCabTyp.pas

### ISSUE THREAD

**Issue by codegraft** [TurboPack/Abbrevia#32]
In AbCabTyp.pas VerifyCab there is a cast from a TStream object to Integer:
https://github.com/TurboPack/Abbrevia/blob/cc2e21e3556a53a6b1944c66d9900cd4ffc65c7b/source/AbCabTyp.pas#L515

This can lead to a crash/exception on 64 bit systems.
Casting to `PtrInt` instead fixes the issue:
```pascal
if FDIIsCabinet(Context, PtrInt(Strm), @Info) then
```

**Comment by romankassebaum** [comment]
Fixed.
