### ISSUE TITLE
Range check error when opening tgz file

### ISSUE THREAD

**Issue by oerjann** [TurboPack/Abbrevia#4]
I can not open the attached tgz file with Abbrevia. 

[ParkLan.zip](https://github.com/TurboPack/Abbrevia/files/439056/ParkLan.zip)
(the tgz file is zipped so that github will accept it)

See code and callstack below

z:=TAbUnzipper.Create(nil);
z.TarAutoHandle:=True;
z.Stream:=str;

:770a96c2 KERNELBASE.RaiseException + 0x62
AbBytes.TAbBytes.StrLCopy($467E179,???,0)
AbBytes.TAbBytes.StrLCopy($57794B0,'',100)
AbBytes.TAbBytes.StrPLCopy($57794B0,'',100)
AbTarTyp.TAbTarItem.SetFileName('')
AbTarTyp.TAbTarItem.Create
AbTarTyp.VerifyTar($7B745F0)
AbBrowse.AbDetermineArcType($7B745F0)
AbZBrows.TAbCustomZipBrowser.SetStream($7B745F0)

**Comment by romankassebaum** [comment]
I just tried to reproduce the issue but had no success. The following code does work:
procedure TForm1.Button1Click(Sender: TObject);
var
  lStream: TStream;
begin
  lStream := TFile.Open('c:\temp\ParkLan.tgz', TFileMode.fmOpen);
  try
    AbUnZipper1.TarAutoHandle := True;
    AbUnZipper1.Stream := lStream;
  finally
    lStream.Free;
  end;
end;

**Comment by oerjann** [comment]
The range check error occurs with the combination of TMemoryStream and a tgz file. TMemoryStream and other file compression format works fine. This issue is not present in the old Abbrevia 5.0 from 2011

This code gives range check error
var
  lStream: TStream;
  mstream: TMemoryStream;
  AbUnZipper1: TAbUnZipper;
begin
  AbUnZipper1:= TAbUnZipper.Create(nil);
  lStream := TFile.Open('c:\temp\ParkLan.tgz', TFileMode.fmOpen);
  mstream:= Tmemorystream.Create;
  mstream.LoadFromStream(lStream);
  try
    AbUnZipper1.TarAutoHandle := True;
    AbUnZipper1.Stream := mStream;
  finally
  lStream.Free;
  mstream.Free;
  AbUnZipper1.Free;
end;

**Comment by romankassebaum** [comment]
Ah, I had to enable range checking, the mem stream doesn't matter.
I could reproduce the problem and hope that I could fix it.
Please try my fixes.

**Comment by oerjann** [comment]
Thank you! That fixed the problem. Your fix also got rid of the irritating exception on line 272 of AbDfOutW.pas that got triggered when opening tgz files:

  {if we've reached the point requested, abort}
  if (FPartSize > 0) and ((FCurrent - FBuffer) >= FPartSize) then
    raise EAbPartSizedInflate.Create(''); {NOTE: This exception is expected during detection of .GZ and .TGZ files. (VerifyGZip)}
