### ISSUE TITLE
Compile error PAnsiChar Pointer Delphi 10.2

### ISSUE THREAD

**Issue by mwoc** [TurboPack/Abbrevia#5]
Using Delphi 10.2 Tokyo, with the latest commit of Abbrevia, I got an error when compiling in AbCharset.pas and AbZipTyp.pas for Win32, during building the package "AbbreviaD240.bpl"

[dcc32 Error] AbCharset.pas(263): E2010 Incompatible types: 'PAnsiChar' and 'Pointer'
[dcc32 Error] AbZipTyp.pas(1494): E2010 Incompatible types: 'PAnsiChar' and 'Pointer'

At those lines, we find:
        OemToCharBuff(@aValue[0], PChar(Result), Length(Result));
        OemToCharBuff(@(pBuffer[0]), PChar(FFileName), Length(FFileName));

Both lines were changed in 58e9ff455fb65d89b7f2000d4802e122e5dcea90

I can compile if I revert the changes to those lines from the mentioned commit, but there's probably something I'm missing - anyone got a hint?

**Comment by romankassebaum** [comment]
The TurboPack version for Abbrevia is located under https://github.com/TurboPack-Tokyo/Abbrevia/.

**Comment by zencode1** [comment]
I'm curious if there is a reason why the Tokyo changes can't be merged into this repository.  It seems to me that it's better to have those changes in a single repo and the repos are the same from commit 9619fe1dfc2c.

**Comment by romankassebaum** [comment]
Currently we are only supporting 10.3.
