### ISSUE TITLE
Error creating new cab using TAbCabArchive

### ISSUE THREAD

**Issue by zencode1** [TurboPack/Abbrevia#6]
When creating a new cab file with TAbCabArchive a EAbFCIAddFileError is thrown with message "FCI cannot add file".  This is due to FCICreate not having been called.  Here is simple code to reproduce the issue:
```
fn := 'somefile.cab'; // use whatever filename you want
cab := TAbCabArchive.Create(fn, fmCreate);
cab.AddFiles('*.*', faAnyFile);  // add whatever files you want (exception here)
cab.Save;
```

To workaround the issue I can add a call to Load which will make a call to FCICreate but this deviates from how other archives are created (such as TAbGzipArchive).

```
fn := 'somefile.cab';
cab := TAbCabArchive.Create(fn, fmCreate);
cab.Load; // forces call to FCICreate
cab.AddFiles('*.*', faAnyFile);
cab.Save;
```

**Comment by zencode1** [comment]
One proposed solution is to add a call to CreateCabFile in TAbCabArchive.Add.  I don't know if this is the correct solution but it works.
```
  if FFCIContext = nil then
    CreateCabFile;
```

**Comment by romankassebaum** [comment]
In which line should I add this?

**Comment by romankassebaum** [comment]
Fixed.
